name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Android CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        cache: gradle
        
    - name: Unit Test
      run: ./gradlew testDebugUnitTest
      # TODO: fix this. Right now the Android Test Report doesn't catch when the Unit Test step fails catastrophically
      # So if there's a build error, Android Test Report passes. Switch to a different test reporting system.
      # continue-on-error: true # IMPORTANT: allow pipeline to continue to Android Test Report step

    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
